app = "acervo-worker"
primary_region = "lax"

[build]
  dockerfile = "../Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "python worker/worker.py"

[deploy]
  strategy = "immediate"
  
[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384
